# Generated by Django 3.2.6 on 2021-08-05 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('model', models.CharField(max_length=128, verbose_name='Model')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('manfactured_year', models.CharField(choices=[('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021')], max_length=64)),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
