# Generated by Django 3.2.6 on 2021-08-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0002_alter_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Fuel type'),
        ),
        migrations.AddField(
            model_name='car',
            name='horsepower',
            field=models.IntegerField(blank=True, null=True, verbose_name='Horsepower'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(upload_to='cars', verbose_name='Image'),
        ),
    ]
